In [1]:
import numpy as np

In [2]:
rand = np.random.RandomState(42)

In [3]:
x = rand.randint(101, size = 10)

In [4]:
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [5]:
[x[3], x[7], x[2]]

[71, 86, 14]

In [6]:
x[[3,7,2]]

array([71, 86, 14])

In [7]:
ind = np.array([3,7,2])

In [8]:
x[ind]

array([71, 86, 14])

In [9]:
ind = np.array([[3,7], [4,5]])

In [10]:
ind

array([[3, 7],
       [4, 5]])

In [11]:
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [12]:
x[ind]

array([[71, 86],
       [60, 20]])

In [13]:
X = np.arange(12).reshape((3,4))

In [14]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
row = np.array([0,1,2])
col = np.array([2,1,3])

In [16]:
X[row, col]

array([ 2,  5, 11])

In [17]:
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])