In [1]:
import numpy as np

In [2]:
x = np.random.randint(10, size = (3,4))

In [3]:
x

array([[9, 6, 8, 8],
       [2, 6, 7, 4],
       [0, 8, 0, 9]])

In [4]:
np.count_nonzero(x)

10

In [5]:
np.sum(x)

67

In [7]:
np.sum( x > 6)

6

In [8]:
np.sum(x == 0)

2

In [9]:
np.sum(x == 0, axis = 0)

array([1, 0, 1, 0])

In [10]:
np.sum(x == 0, axis = 1)

array([0, 0, 2])

In [11]:
np.any(x == 0)

True

In [12]:
np.all(x == 0)

False

In [13]:
np.any(x == 0, axis = 1)

array([False, False,  True])

In [14]:
x

array([[9, 6, 8, 8],
       [2, 6, 7, 4],
       [0, 8, 0, 9]])

In [15]:
x < 5

array([[False, False, False, False],
       [ True, False, False,  True],
       [ True, False,  True, False]])

In [16]:
x[x<5]

array([2, 4, 0, 0])

In [17]:
y = np.random.randint(10, size = 12)

In [18]:
y

array([5, 3, 3, 6, 2, 4, 2, 3, 3, 7, 5, 5])

In [19]:
y_b = np.array([True, False])

In [20]:
y[y_b]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 12 but corresponding boolean dimension is 2

In [21]:
y

array([5, 3, 3, 6, 2, 4, 2, 3, 3, 7, 5, 5])

In [22]:
y[y < 5]

array([3, 3, 2, 4, 2, 3, 3])

In [23]:
a = np.random.randint(10, size = (5,3))

In [24]:
a

array([[5, 8, 3],
       [3, 2, 5],
       [7, 4, 1],
       [4, 4, 5],
       [5, 1, 3]])

In [25]:
a_b = np.array([True, False])

In [26]:
a[a_b]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 2

In [27]:
a_b2 = np.array([True, False, True])

In [28]:
a[a_b2]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3

In [29]:
a_b3 = np.array([True, False, True, False, False])

In [30]:
a[a_b3]

array([[5, 8, 3],
       [7, 4, 1]])

In [31]:
a.shape

(5, 3)

In [32]:
a_b3.shape

(5,)

In [33]:
a_b3

array([ True, False,  True, False, False])

In [34]:
a_b4 = a_b3.reshape((1,5))

In [35]:
a_b4

array([[ True, False,  True, False, False]])

In [36]:
a[a_b4]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 1

In [37]:
a

array([[5, 8, 3],
       [3, 2, 5],
       [7, 4, 1],
       [4, 4, 5],
       [5, 1, 3]])

In [38]:
a_b3

array([ True, False,  True, False, False])

In [39]:
a[a_b3]

array([[5, 8, 3],
       [7, 4, 1]])

In [40]:
x

array([[9, 6, 8, 8],
       [2, 6, 7, 4],
       [0, 8, 0, 9]])

In [41]:
a[a>4]

array([5, 8, 5, 7, 5, 5])

In [42]:
a>4

array([[ True,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False]])