In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,5])

In [4]:
x < 3

array([ True,  True, False, False, False])

In [5]:
x > 3

array([False, False, False,  True,  True])

In [6]:
x <= 3

array([ True,  True,  True, False, False])

In [7]:
x >= 3

array([False, False,  True,  True,  True])

In [8]:
x != 3

array([ True,  True, False,  True,  True])

In [9]:
x == 3

array([False, False,  True, False, False])

In [10]:
np.equal(x,3)

array([False, False,  True, False, False])

In [11]:
x == 3

array([False, False,  True, False, False])

In [12]:
np.not_equal(x,3)

array([ True,  True, False,  True,  True])

In [13]:
x != 3

array([ True,  True, False,  True,  True])

In [14]:
np.less(x,3)

array([ True,  True, False, False, False])

In [15]:
x < 3

array([ True,  True, False, False, False])

In [16]:
np.less_equal(x,3)

array([ True,  True,  True, False, False])

In [17]:
x <= 3

array([ True,  True,  True, False, False])

In [18]:
np.greater(x, 3)

array([False, False, False,  True,  True])

In [19]:
x > 3

array([False, False, False,  True,  True])

In [20]:
np.greater_equal(x, 3)

array([False, False,  True,  True,  True])

In [21]:
x >= 3

array([False, False,  True,  True,  True])

In [23]:
np.random.seed(0)

In [29]:
np.random.randint(10, size=(3,4))

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [31]:
x.shape

(5,)

In [32]:
x.ndim

1

In [33]:
x.size

5

In [1]:
import numpy as np

In [3]:
x = np.random.randint(10, size=(3,4))

In [4]:
x

array([[9, 4, 2, 3],
       [6, 3, 2, 2],
       [4, 0, 2, 9]])

In [5]:
np.less(x,6)

array([[False,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False]])

In [6]:
x < 6

array([[False,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False]])

In [7]:
np.count_nonzero(x < 6)

9

In [8]:
np.count_nonzero(np.less(x,6))

9

In [10]:
x.size - np.count_nonzero(x < 6)

3

In [11]:
np.sum(x < 6)

9

In [12]:
x

array([[9, 4, 2, 3],
       [6, 3, 2, 2],
       [4, 0, 2, 9]])

In [13]:
x < 6

array([[False,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False]])

In [14]:
np.sum(x < 6, axis = 1)

array([3, 3, 3])

In [15]:
np.sum(x < 6, axis = 0)

array([1, 3, 3, 2])

In [16]:
np.any(x > 8)

True

In [17]:
np.any(x > 8, axis = 0)

array([ True, False, False,  True])

In [18]:
np.any(x > 8, axis = 1)

array([ True, False,  True])

In [19]:
np.all(x < 10)

True

In [20]:
np.all(x > 10)

False

In [21]:
np.all(x > 8)

False

In [22]:
np.all(x > 8, axis = 0)

array([False, False, False, False])

In [23]:
np.all(x > 8, axis = 1)

array([False, False, False])

In [24]:
np.all(x == 6)

False

In [25]:
np.any(x == 6)

True

In [26]:
np.any(x == 6, axis = 1)

array([False,  True, False])

In [27]:
x

array([[9, 4, 2, 3],
       [6, 3, 2, 2],
       [4, 0, 2, 9]])

In [28]:
np.any(x == 6, axis = 0)

array([ True, False, False, False])

In [29]:
x

array([[9, 4, 2, 3],
       [6, 3, 2, 2],
       [4, 0, 2, 9]])

In [30]:
(x < 8) & (x > 4)

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [31]:
np.sum( (x < 8) & (x > 4) )

1

In [32]:
np.sum( (x < 8) & (x > 4), axis = 0 )

array([1, 0, 0, 0])

In [33]:
np.bitwise_and(x < 8, x > 4)

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [34]:
np.bitwise_and( np.less(x,8), np.greater(x, 4) )

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [35]:
x

array([[9, 4, 2, 3],
       [6, 3, 2, 2],
       [4, 0, 2, 9]])

In [36]:
x > 5

array([[ True, False, False, False],
       [ True, False, False, False],
       [False, False, False,  True]])

In [37]:
x[x > 5]

array([9, 6, 9])

In [38]:
x [True]

array([[[9, 4, 2, 3],
        [6, 3, 2, 2],
        [4, 0, 2, 9]]])

In [39]:
X_true = x > 6

In [40]:
X_true

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [41]:
X_true[True]

array([[[ True, False, False, False],
        [False, False, False, False],
        [False, False, False,  True]]])

In [42]:
X_true[x > 6]

array([ True,  True])

In [43]:
x

array([[9, 4, 2, 3],
       [6, 3, 2, 2],
       [4, 0, 2, 9]])

In [44]:
x[x > 6]

array([9, 9])

In [45]:
x

array([[9, 4, 2, 3],
       [6, 3, 2, 2],
       [4, 0, 2, 9]])

In [46]:
x[[1,1,0,1]]

array([[6, 3, 2, 2],
       [6, 3, 2, 2],
       [9, 4, 2, 3],
       [6, 3, 2, 2]])

In [47]:
X_true

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [48]:
X_true.astype(int)

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1]])

In [49]:
x

array([[9, 4, 2, 3],
       [6, 3, 2, 2],
       [4, 0, 2, 9]])

In [50]:
x[X_true.astype(int)]

array([[[6, 3, 2, 2],
        [9, 4, 2, 3],
        [9, 4, 2, 3],
        [9, 4, 2, 3]],

       [[9, 4, 2, 3],
        [9, 4, 2, 3],
        [9, 4, 2, 3],
        [9, 4, 2, 3]],

       [[9, 4, 2, 3],
        [9, 4, 2, 3],
        [9, 4, 2, 3],
        [6, 3, 2, 2]]])

In [1]:
import numpy as np

In [2]:
a=np.random.randint(10, size=10)

In [3]:
a

array([2, 1, 8, 2, 7, 8, 1, 2, 6, 4])

In [4]:
b = np.array([True, False, True])

In [5]:
a[b]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 3

In [6]:
c = np.random.randint(10, size=10)

In [7]:
c

array([6, 3, 3, 0, 6, 5, 0, 1, 0, 0])

In [12]:
c_bool = c > 3

In [13]:
c_bool


array([ True, False, False, False,  True,  True, False, False, False,
       False])

In [14]:
a

array([2, 1, 8, 2, 7, 8, 1, 2, 6, 4])

In [15]:
a[c_bool]

array([2, 7, 8])

In [16]:
c_bool2 = c_bool.reshape((1,10))

In [17]:
c_bool2

array([[ True, False, False, False,  True,  True, False, False, False,
        False]])

In [18]:
a

array([2, 1, 8, 2, 7, 8, 1, 2, 6, 4])

In [19]:
a[c_bool2]

IndexError: too many indices for array