In [1]:
import numpy as np

## NumPy indexing and selecting

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[9]

9

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[0:5] = 100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0, 11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr = arr[:6]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_arr[:] = 99

In [14]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [17]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
arr_2d[1][0]

20

In [19]:
arr_2d[2,1]

40

In [20]:
arr_2d[0:2, 1:3]

array([[10, 15],
       [25, 30]])

## Conditional Selection

In [21]:
arr = np.arange(0, 11)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [24]:
bool_arr = arr > 5

In [25]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [26]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [27]:
arr[arr > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [28]:
arr_2d = np.arange(50).reshape(5, 10)

In [29]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [30]:
arr_2d[1:3, 2:4]

array([[12, 13],
       [22, 23]])