In [1]:
import numpy as np

In [2]:
values = np.random.randint(1,10, size = 100)

In [3]:
1/values

array([0.25      , 0.5       , 0.25      , 0.33333333, 0.11111111,
       0.2       , 1.        , 0.33333333, 0.25      , 0.5       ,
       0.5       , 0.11111111, 0.16666667, 0.11111111, 0.5       ,
       0.16666667, 0.25      , 0.14285714, 0.33333333, 0.25      ,
       0.25      , 0.33333333, 0.11111111, 0.16666667, 0.5       ,
       0.2       , 0.33333333, 0.11111111, 0.11111111, 0.11111111,
       0.11111111, 0.25      , 0.125     , 0.5       , 0.33333333,
       0.125     , 1.        , 0.5       , 0.11111111, 0.2       ,
       0.33333333, 0.33333333, 1.        , 0.25      , 0.14285714,
       0.125     , 0.14285714, 0.2       , 0.11111111, 0.11111111,
       0.11111111, 0.33333333, 0.33333333, 1.        , 0.2       ,
       0.11111111, 0.2       , 0.25      , 0.25      , 0.25      ,
       0.2       , 0.11111111, 0.11111111, 1.        , 0.25      ,
       0.125     , 0.11111111, 0.2       , 0.125     , 0.25      ,
       0.33333333, 0.2       , 0.25      , 0.125     , 0.33333

In [6]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

векторлардың формасы бірдей болуы тиіс екен

In [5]:
np.arange(7) / np.arange(5)

ValueError: operands could not be broadcast together with shapes (7,) (5,) 

In [7]:
 x = np.arange(9)

In [8]:
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
x = x.reshape((3,3))

In [10]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
x*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [12]:
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [13]:
x = np.arange(4)

In [14]:
x

array([0, 1, 2, 3])

In [15]:
x+5

array([5, 6, 7, 8])

In [16]:
x-5

array([-5, -4, -3, -2])

In [17]:
x*2

array([0, 2, 4, 6])

In [18]:
x/2

array([0. , 0.5, 1. , 1.5])

In [19]:
x//2

array([0, 0, 1, 1])

In [20]:
-x

array([ 0, -1, -2, -3])

In [21]:
x**2

array([0, 1, 4, 9])

In [22]:
x % 2

array([0, 1, 0, 1])

In [23]:
x

array([0, 1, 2, 3])

In [24]:
x

array([0, 1, 2, 3])

In [25]:
np.add(x, 2)

array([2, 3, 4, 5])

In [26]:
x+2

array([2, 3, 4, 5])

In [27]:
np.subtract(x,2)

array([-2, -1,  0,  1])

In [28]:
x-2

array([-2, -1,  0,  1])

In [29]:
np.multiply(x,2)

array([0, 2, 4, 6])

In [30]:
x*2

array([0, 2, 4, 6])

In [31]:
np.divide(x, 2)

array([0. , 0.5, 1. , 1.5])

In [32]:
np.floor_divide(x, 2)

array([0, 0, 1, 1])

In [33]:
x

array([0, 1, 2, 3])

In [34]:
x/2

array([0. , 0.5, 1. , 1.5])

In [35]:
x//2

array([0, 0, 1, 1])

In [36]:
np.negative(x)

array([ 0, -1, -2, -3])

In [37]:
-x

array([ 0, -1, -2, -3])

In [38]:
np.power(x, 2)

array([0, 1, 4, 9])

In [39]:
x ** 2

array([0, 1, 4, 9])

In [40]:
np.mod(x,2)

array([0, 1, 0, 1])

In [41]:
x % 2

array([0, 1, 0, 1])

In [42]:
x1 = np.array([-2, -1, 0, 1, 2])

In [43]:
x1

array([-2, -1,  0,  1,  2])

In [44]:
abs(x1)

array([2, 1, 0, 1, 2])

In [45]:
np.absolute(x1)

array([2, 1, 0, 1, 2])

In [47]:
np.abs(x1)

array([2, 1, 0, 1, 2])

In [48]:
x = np.linspace(0, np.pi, 3)

In [49]:
x

array([0.        , 1.57079633, 3.14159265])

In [50]:
np.sin(x)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [51]:
np.cos(x)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [52]:
np.tan(x)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [53]:
np.arcsin(x)

/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.


array([ 0., nan, nan])

In [59]:
x2 = np.array([-1, 0, 1])

In [60]:
x2

array([-1,  0,  1])

In [62]:
np.arcsin(x2)

array([-1.57079633,  0.        ,  1.57079633])

In [63]:
 np.arccos(x2)

array([3.14159265, 1.57079633, 0.        ])

In [64]:
np.arcsin(x2)

array([-1.57079633,  0.        ,  1.57079633])

In [65]:
np.arctan(x2)

array([-0.78539816,  0.        ,  0.78539816])

In [66]:
3.15/4

0.7875

In [70]:
x=np.array([1,2,3])

In [71]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [72]:
2**x

array([2, 4, 8])

In [73]:
np.exp2(x)

array([2., 4., 8.])

In [74]:
np.power(3, x)

array([ 3,  9, 27])

In [77]:
np.exp3(x)

AttributeError: module 'numpy' has no attribute 'exp3'

In [78]:
x=np.array([1, 2, 4, 10])

In [79]:
x

array([ 1,  2,  4, 10])

In [80]:
np.log(x)

array([0.        , 0.69314718, 1.38629436, 2.30258509])

In [81]:
np.log2(x)

array([0.        , 1.        , 2.        , 3.32192809])

In [82]:
np.log10(x)

array([0.        , 0.30103   , 0.60205999, 1.        ])

In [83]:
x = np.arange(5)
y = np.empty(5)

In [86]:
np.multiply(x, 10, out = y)

array([ 0., 10., 20., 30., 40.])

In [87]:
y

array([ 0., 10., 20., 30., 40.])

In [88]:
y = np.zeros(10)

In [89]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [91]:
np.power(2, x)

array([ 1,  2,  4,  8, 16])

In [92]:
x

array([0, 1, 2, 3, 4])

In [93]:
np.power(2, x, out = y[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [94]:
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [95]:
x = np.arange(1,6)

In [96]:
x

array([1, 2, 3, 4, 5])

In [97]:
np.add.reduce(x)

15

In [98]:
np.multiply.reduce(x)

120

In [99]:
np.power.reduce(x)

1

In [100]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [101]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [102]:
x

array([1, 2, 3, 4, 5])

In [103]:
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [104]:
np.add.outer(x, x)

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [105]:
l = np.random.random(size=100)

In [106]:
l

array([0.59236258, 0.83167927, 0.86733444, 0.54981099, 0.37777638,
       0.72092437, 0.29946281, 0.68562565, 0.68489045, 0.62015978,
       0.4304652 , 0.84643959, 0.42502914, 0.15976682, 0.9440771 ,
       0.38974494, 0.28064077, 0.9358326 , 0.16111899, 0.26557258,
       0.06172499, 0.16653053, 0.20085632, 0.76855876, 0.82215332,
       0.57112753, 0.09659056, 0.30826981, 0.36512578, 0.14745131,
       0.88268543, 0.16783966, 0.24952746, 0.30699059, 0.43799268,
       0.75307475, 0.71553158, 0.72458563, 0.80224731, 0.08847538,
       0.70123064, 0.31651101, 0.40909637, 0.46265209, 0.82137078,
       0.45753864, 0.88935297, 0.34395109, 0.62614946, 0.36412952,
       0.51109094, 0.61732623, 0.6073732 , 0.10724223, 0.36011567,
       0.60523415, 0.16867013, 0.17216574, 0.4373008 , 0.78802277,
       0.79875778, 0.75511968, 0.12824076, 0.27427237, 0.24696893,
       0.98047972, 0.74688503, 0.77531767, 0.11080119, 0.41023509,
       0.22603812, 0.87019506, 0.44275363, 0.22063664, 0.62427

In [107]:
np.sum(l)

50.481076542704315

In [108]:
big_array = np.random.rand(1000000)

In [109]:
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 3: 146 ms per loop
1000 loops, best of 3: 926 µs per loop


In [110]:
big_array


array([0.71372869, 0.57526793, 0.57611297, ..., 0.80878941, 0.85120727,
       0.7502018 ])

In [111]:
np.min(big_array)

2.55040678798224e-07

In [112]:
np.max(big_array)

0.9999983348614614

In [113]:
%timeit min(big_array)
%timeit np.min(big_array)

10 loops, best of 3: 102 ms per loop
1000 loops, best of 3: 890 µs per loop


In [114]:
big_array.sum()

500129.8129225196

In [115]:
big_array.min()

2.55040678798224e-07

In [116]:
big_array.max()

0.9999983348614614

In [117]:

M = np.random.random((3,4))


In [118]:
M

array([[0.14094748, 0.11269382, 0.65558216, 0.4995647 ],
       [0.44682404, 0.90916915, 0.40107764, 0.76049189],
       [0.75904533, 0.43979537, 0.97149154, 0.94015082]])

In [119]:
M.sum()

7.03683396045791

In [120]:
M.max()

0.9714915365703464

In [121]:
M.min()

0.11269382267584382

In [122]:
M.min(axis=0)

array([0.14094748, 0.11269382, 0.40107764, 0.4995647 ])

In [124]:
M.max(axis = 0)

array([0.75904533, 0.90916915, 0.97149154, 0.94015082])

In [125]:
M.min(axis=1
     )

array([0.11269382, 0.40107764, 0.43979537])

In [126]:
M.sum(axis=1)

array([1.40878817, 2.51756273, 3.11048306])

In [127]:
M.sum(axis=0)

array([1.34681685, 1.46165835, 2.02815134, 2.20020742])

In [128]:
np.__version__

'1.14.0'

In [1]:
import numpy as np

In [2]:
x = np.random.randint(10, size = 10)

In [3]:
x

array([0, 0, 1, 8, 9, 4, 4, 2, 4, 1])

In [4]:
np.sum(x)

33

In [7]:
y = np.empty(shape= 10)

In [8]:
y

array([1.53236081e-316, 5.95832805e+271, 5.95667713e+271, 5.95750259e+271,
       5.95667713e+271, 5.95915351e+271, 5.95667713e+271, 6.01334434e-154,
       1.58101007e-322, 0.00000000e+000])

In [9]:
np.prod(x)

0

In [11]:
np.mean(x)

3.3

In [13]:
np.std(x)

3.0016662039607267

In [14]:
np.var(x)

9.01

In [15]:
np.median(x)

3.0

In [16]:
np.min(x)

0

In [17]:
np.max(x)

9

In [18]:
np.argmin(x)

0

In [19]:
np.argmax(x)

4

In [20]:
x

array([0, 0, 1, 8, 9, 4, 4, 2, 4, 1])

In [22]:
np.any(x)

True

In [23]:
np.all(x)

False