In [1]:
import numpy as np
np.random.seed(0)

In [2]:
x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3 = np.random.randint(10, size = (3,4,5))

In [3]:
x1

array([5, 0, 3, 3, 7, 9])

In [4]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [5]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [6]:
x4 = np.random.randint(10, size = (3,4,5,2))

In [7]:
x4

array([[[[4, 3],
         [4, 4],
         [8, 4],
         [3, 7],
         [5, 5]],

        [[0, 1],
         [5, 9],
         [3, 0],
         [5, 0],
         [1, 2]],

        [[4, 2],
         [0, 3],
         [2, 0],
         [7, 5],
         [9, 0]],

        [[2, 7],
         [2, 9],
         [2, 3],
         [3, 2],
         [3, 4]]],


       [[[1, 2],
         [9, 1],
         [4, 6],
         [8, 2],
         [3, 0]],

        [[0, 6],
         [0, 6],
         [3, 3],
         [8, 8],
         [8, 2]],

        [[3, 2],
         [0, 8],
         [8, 3],
         [8, 2],
         [8, 4]],

        [[3, 0],
         [4, 3],
         [6, 9],
         [8, 0],
         [8, 5]]],


       [[[9, 0],
         [9, 6],
         [5, 3],
         [1, 8],
         [0, 4]],

        [[9, 6],
         [5, 7],
         [8, 8],
         [9, 2],
         [8, 6]],

        [[6, 9],
         [1, 6],
         [8, 8],
         [3, 2],
         [3, 6]],

        [[3, 6],
         [5, 7],
     

In [8]:
x5 = np.random.randint(10, size = (2, 3, 4, 5, 6))

In [9]:
x5

array([[[[[2, 3, 9, 7, 5, 3],
          [4, 5, 3, 3, 7, 9],
          [9, 9, 7, 3, 2, 3],
          [9, 7, 7, 5, 1, 2],
          [2, 8, 1, 5, 8, 4]],

         [[0, 2, 5, 5, 0, 8],
          [1, 1, 0, 3, 8, 8],
          [4, 4, 0, 9, 3, 7],
          [3, 2, 1, 1, 2, 1],
          [4, 2, 5, 5, 5, 2]],

         [[5, 7, 7, 6, 1, 6],
          [7, 2, 3, 1, 9, 5],
          [9, 9, 2, 0, 9, 1],
          [9, 0, 6, 0, 4, 8],
          [4, 3, 3, 8, 8, 7]],

         [[0, 3, 8, 7, 7, 1],
          [8, 4, 7, 0, 4, 9],
          [0, 6, 4, 2, 4, 6],
          [3, 3, 7, 8, 5, 0],
          [8, 5, 4, 7, 4, 1]]],


        [[[3, 3, 9, 2, 5, 2],
          [3, 5, 7, 2, 7, 1],
          [6, 5, 0, 0, 3, 1],
          [9, 9, 6, 6, 7, 8],
          [8, 7, 0, 8, 6, 8]],

         [[9, 8, 3, 6, 1, 7],
          [4, 9, 2, 0, 8, 2],
          [7, 8, 4, 4, 1, 7],
          [6, 9, 4, 1, 5, 9],
          [7, 1, 3, 5, 7, 3]],

         [[6, 6, 7, 9, 1, 9],
          [6, 0, 3, 8, 4, 1],
          [4, 5, 0, 3, 1, 

In [10]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [11]:
x3.ndim

3

In [12]:
x3.shape

(3, 4, 5)

In [13]:
x3.size

60

In [14]:
x3.dtype

dtype('int64')

In [15]:
x3.itemsize

8

In [16]:
x3.nbytes

480

In [17]:
x1

array([5, 0, 3, 3, 7, 9])

In [18]:
x1[0]

5

In [19]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [20]:
x2[0]

array([3, 5, 2, 4])

In [21]:
x2[0, :]

array([3, 5, 2, 4])

In [22]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [23]:
x1

array([5, 0, 3, 3, 7, 9])

In [24]:
x1[-1]

9

In [25]:
x1[-2]

7

In [26]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [27]:
x2[-1]

array([1, 6, 7, 7])

In [28]:
x2[0, 0]

3

In [29]:
x2[2, 0]

1

In [30]:
x2[0,0]=12

In [31]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [32]:
x = np.arange(10)

In [33]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
x[:5]

array([0, 1, 2, 3, 4])

In [35]:
x[5:]

array([5, 6, 7, 8, 9])

In [36]:
x[4:7]

array([4, 5, 6])

In [37]:
x[::2]

array([0, 2, 4, 6, 8])

In [39]:
x[1::2]

array([1, 3, 5, 7, 9])

In [40]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [41]:
x[5::-2]

array([5, 3, 1])

In [42]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [43]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [44]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [45]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [46]:
x2[:, 0]

array([12,  7,  1])

In [47]:
x2[0, :]

array([12,  5,  2,  4])

In [48]:
x2[0]

array([12,  5,  2,  4])

In [50]:
x2[1]

array([7, 6, 8, 8])

In [51]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [52]:
x4

array([[[[4, 3],
         [4, 4],
         [8, 4],
         [3, 7],
         [5, 5]],

        [[0, 1],
         [5, 9],
         [3, 0],
         [5, 0],
         [1, 2]],

        [[4, 2],
         [0, 3],
         [2, 0],
         [7, 5],
         [9, 0]],

        [[2, 7],
         [2, 9],
         [2, 3],
         [3, 2],
         [3, 4]]],


       [[[1, 2],
         [9, 1],
         [4, 6],
         [8, 2],
         [3, 0]],

        [[0, 6],
         [0, 6],
         [3, 3],
         [8, 8],
         [8, 2]],

        [[3, 2],
         [0, 8],
         [8, 3],
         [8, 2],
         [8, 4]],

        [[3, 0],
         [4, 3],
         [6, 9],
         [8, 0],
         [8, 5]]],


       [[[9, 0],
         [9, 6],
         [5, 3],
         [1, 8],
         [0, 4]],

        [[9, 6],
         [5, 7],
         [8, 8],
         [9, 2],
         [8, 6]],

        [[6, 9],
         [1, 6],
         [8, 8],
         [3, 2],
         [3, 6]],

        [[3, 6],
         [5, 7],
     

In [53]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [54]:
x3[0]

array([[8, 1, 5, 9, 8],
       [9, 4, 3, 0, 3],
       [5, 0, 2, 3, 8],
       [1, 3, 3, 3, 7]])

In [55]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [56]:
x2_sub = x2[:2, :2]

In [57]:
x2_sub

array([[12,  5],
       [ 7,  6]])

In [58]:
x2_sub[0, 0] = 99

In [59]:
x2_sub

array([[99,  5],
       [ 7,  6]])

In [60]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [61]:
x2_sub_copy = x2_sub.copy()

In [62]:
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [63]:
x2_sub_copy[0, 0] = 42

In [64]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [65]:
grid = np.arange(1, 10).reshape((3,3))

In [66]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
x  = np.array([1,2,3])

In [68]:
x

array([1, 2, 3])

In [69]:
x.reshape((1,3))

array([[1, 2, 3]])

In [70]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [71]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [72]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [74]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [75]:
np.concatenate([y,x])

array([3, 2, 1, 1, 2, 3])

In [76]:
z = np.array([99,99,99])

In [77]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [78]:
z1 = np.array([100,100])

In [79]:
np.concatenate([x, z1])

array([  1,   2,   3, 100, 100])

In [80]:
grid = np.array([[1,2,3], [4,5,6]])

In [81]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [83]:
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [84]:
x

array([1, 2, 3])

In [85]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
np.vstack([grid, x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [88]:
z2 = x.reshape((1,3))

In [89]:
np.concatenate([grid, z2], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [92]:
z3 = x.reshape((3,1))

In [93]:
z3

array([[1],
       [2],
       [3]])

In [97]:
x

array([1, 2, 3])

In [98]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
x = np.array([1,2,3,99,99,3,2,1])

In [101]:
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [102]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [103]:
m1,m2,m3 = np.split(x, [3,5])

In [104]:
m1

array([1, 2, 3])

In [105]:
m2

array([99, 99])

In [106]:
m3

array([3, 2, 1])

In [109]:
np.split(np.arange(16).reshape((4,4)), [2], axis = 0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [111]:
np.split(np.arange(16).reshape((4,4)), [3], axis=1)

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]