## NumPy array


In [1]:
import numpy as np


In [2]:
my_list = [2,6,8]

In [3]:
my_list

[2, 6, 8]

In [4]:
my_array = np.array(my_list)

In [5]:
my_array

array([2, 6, 8])

In [6]:
my_2_list = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
my_2_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
my_matrix = np.array(my_2_list)

In [10]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
np.random.randn(5)

array([ 0.27659155,  1.4437755 , -0.32257488,  0.2472922 ,  1.30615714])

In [23]:
np.random.rand(5)

array([0.88098999, 0.12704226, 0.98471435, 0.73144645, 0.59398494])

In [24]:
np.random.rand(5,5)

array([[0.53886565, 0.3580037 , 0.46883012, 0.83445149, 0.24047015],
       [0.00396288, 0.49341011, 0.7264319 , 0.07181972, 0.29831156],
       [0.35569348, 0.05996257, 0.89694311, 0.59430295, 0.05054069],
       [0.21189417, 0.97929928, 0.24808989, 0.74639432, 0.55371255],
       [0.0181492 , 0.21148782, 0.81893034, 0.39849029, 0.44516267]])

In [25]:
np.random.rand(5,5,3)

array([[[0.77349398, 0.08844162, 0.07600065],
        [0.73291731, 0.9153564 , 0.72933874],
        [0.81587987, 0.05185517, 0.9232942 ],
        [0.48392261, 0.31828544, 0.94737386],
        [0.10023015, 0.04494165, 0.11678575]],

       [[0.01732398, 0.54257408, 0.61258024],
        [0.43603157, 0.33922506, 0.44393164],
        [0.33228591, 0.2820182 , 0.92746266],
        [0.33469731, 0.30189128, 0.51334146],
        [0.27175157, 0.30463108, 0.28697557]],

       [[0.34645744, 0.9058116 , 0.99681346],
        [0.27259739, 0.69569413, 0.15443657],
        [0.52016244, 0.89869202, 0.8913905 ],
        [0.1794425 , 0.23151047, 0.26978156],
        [0.6248491 , 0.94971139, 0.85325345]],

       [[0.42883819, 0.45959074, 0.59884754],
        [0.72388234, 0.44855089, 0.83546521],
        [0.73849326, 0.04949948, 0.22481999],
        [0.61039549, 0.67196663, 0.92517009],
        [0.90183737, 0.22479796, 0.62654821]],

       [[0.28404492, 0.25536219, 0.69120417],
        [0.21095588, 0.332

In [26]:
np.random.randn(4)

array([-0.07914128,  0.06959631, -0.35762039,  0.06869284])

In [27]:
np.random.randn(3,2,2)

array([[[ 0.97624487,  0.92298918],
        [-1.38239357, -1.72660605]],

       [[-0.46180092, -0.28073077],
        [ 0.36597689, -1.02784431]],

       [[ 1.52404196,  0.1553195 ],
        [ 0.32428719, -0.17978979]]])

In [28]:
np.random.randint(10)

8

In [29]:
np.random.randint(0, 10)

6

In [30]:
np.random.randint(0, 10, 5)

array([2, 2, 0, 2, 9])

In [31]:
np.random.randint(0, 10, (3,4))

array([[0, 8, 1, 4],
       [7, 1, 3, 7],
       [8, 7, 1, 6]])

In [32]:
np.random.randint(0, 10, (3,4,3))

array([[[3, 0, 3],
        [9, 5, 4],
        [1, 1, 0],
        [2, 6, 9]],

       [[6, 7, 9],
        [6, 7, 0],
        [9, 0, 8],
        [8, 8, 5]],

       [[0, 9, 9],
        [4, 5, 3],
        [1, 7, 7],
        [4, 2, 8]]])

In [33]:
arr = np.arange(25)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
intarr = np.random.randint(0, 50, 10)

In [37]:
intarr.reshape(2,5)

array([[37, 17, 34,  1, 22],
       [48, 13, 20, 12,  8]])

In [38]:
intarr.max(0)

48

In [39]:
np.max(intarr)

48

In [40]:
intarr.min()


1

In [41]:
np.min(intarr)

1

In [42]:
intarr

array([37, 17, 34,  1, 22, 48, 13, 20, 12,  8])

In [43]:
intarr.argmax()

5

In [44]:
np.argmax(intarr)

5

In [45]:
np.argmin(intarr)

3

In [46]:
arr.shape

(25,)

In [47]:
intarr.shape

(10,)

In [49]:
np.reshape(arr, (5,5)).shape

(5, 5)